- _layouts/about.html
- _layouts/fibf-new.html
- pages/ssgb.md
> Revert "Staging"

- _pages/performance-management.md
> Text edits for performance management

- _assets/css/_performance-management.scss
- _pages/performance-management.md
Fix accordion icon showing on the performance management page.
> Icons in accordion

- _pages/performance-management.md
Text edits for performance management page
> Text Edits

- _includes/governance/members.html
- _includes/meta.html
- _layouts/governance/council.html
- _layouts/governance/representative.html
- _layouts/governance/sapoc.html
- _pages/governance/governance-board.md
- _pages/performance-management.md
- _sass/governance.scss
1. Fixed 508 errors detected by the ANDI tool
2. Added OG tag for SSGB page
3. Fixed some responsive issues
> QA edits for SSGB/SOPAC

- _layouts/page.html
- _pages/faq.md
1. New FAQ page /faq
2. Added banner to page layout, need 'banner' variable set to true in order to show generic banner.
> FAQ Page, edits to general page template

- _pages/faq.md
- _sass/global.scss
- assets/images/accordion-add-white.svg
- assets/images/accordion-remove-white.svg
Changed FAQ content to accordion. Edited global scss for accordions that have a certain class.
> FAQ - Accordion

- _includes/pm/evidence-based-pm.html
- _sass/global.scss
Added responsive vimeo video to modal and javascript to make the video stop when the modal is closed.
> Homepage video/modal

- _includes/news-and-update.html
- index.html
Added section IDs, News Articles, Title Tag
> Homepage edits

- _config.yml
- _includes/meta.html
- index.html
1. Changed site config title
2. Remove appended site title to homepage title tag
3. Renamed homepage title
> Meta/Title Tags

- _includes/news/static-news-listing-home.html
- _pages/public-comment/public-comment-open-enhancing-practices-to-optimize-cost-recovery.md
Added new public comment page, edited home news block
> News item/page

- _config.yml
- _includes/landing_top.html
- _includes/news-and-update.html
- _sass/global.scss
- _sass/resources.scss
1. Styled main menu to have blocks around links
2. Renamed main menu links
3. Reordered main menu
> Main Menu Styling/Renaming

- _includes/menu.html
- _includes/notifications.html
1. Add news modal to homepage header
2. Fetch request in javascript to url: /news-api/
3. Filter results to month, else set no new notifications
4. If results, adjust modal, showing news article links
> Header notification button, pulls data from json

- _config.yml
- _includes/side-nav.html
Jira Story - 
https://cm-jira.usa.gov/browse/ECASOGP-12279
Preview Link - 
https://federalist-4be496a3-cca3-4187-b4d4-c3d573ae3139.sites.pages.cloud.gov/preview/gsa/ussm/staging/
> ECASOGP-12279

- _includes/fm/capabilities.html
Preview Link - https://federalist-4be496a3-cca3-4187-b4d4-c3d573ae3139.sites.pages.cloud.gov/preview/gsa/ussm/ECASOGP-13880/
Make sure there are 89 entries in "Business Capabilities", and nothing is getting cut off.
In addition, I made all the content top based (_vertically _aligned) per the PO.
Jira story - 
https://cm-jira.usa.gov/browse/ECASOGP-13880
> Ecasogp 13880

- _data/fm.json
Fixed Ordering - 
https://federalist-4be496a3-cca3-4187-b4d4-c3d573ae3139.sites.pages.cloud.gov/preview/gsa/ussm/ECASOGP-13880/fibf-fm/
(Under FFM0.20)
> fixed ordering

- assets/css/index.scss
i accidentally merged these two, and there are pre-mature pushes
> Revert "Updating ALL of HCM"

- _config.yml
- _includes/landing_top.html
- _layouts/performance-management.html
- _pages/Governance.md
- _pages/marketplace/financial-management.md
- _pages/marketplace/grants-management.md
- _pages/marketplace/human-capital-management.md
- _pages/marketplace/marketplace2.md
- _pages/marketplace/travel-expense.md
[](url)Changes Approved by PO
[Jira Story](https://cm-jira.usa.gov/browse/OGPWEB-17235)
Updated the layout of the governance page to utilize the site wide performance management layout
I updated the image attached to wrap around the sections and formatted it with the new layout.
[Preview Link](https://federalist-4be496a3-cca3-4187-b4d4-c3d573ae3139.sites.pages.cloud.gov/preview/gsa/ussm/OGPWEB-17235-gov/governance/)
> Update Governance Layout

- _includes/landing_top.html
- _includes/scripts.html
- _pages/marketplace/marketplace2.md
QSMO Filter fixed as a part of  the story [OGPWEB-17415]
Preview link:
https://federalist-4be496a3-cca3-4187-b4d4-c3d573ae3139.sites.pages.cloud.gov/preview/gsa/ussm/QSMO-Filter-FIX-OGPWEB-17415/qsmo/#subject=*&role=*&status=*
changes approved by PO
> Qsmo filter fix ogpweb 17415

- _includes/landing_top.html
- _pages/marketplace/marketplace.html
**Changes approved by PO**
Update marketplace page to format SAM data on shared services table
Update marketplace to remove json descriptions from table as requested
[Jira Story](https://cm-jira.usa.gov/browse/OGPWEB-17899)
[Preview Link](https://federalist-4be496a3-cca3-4187-b4d4-c3d573ae3139.sites.pages.cloud.gov/preview/gsa/ussm/OGPWEB-17899-grm/marketplace/grm/)
> Ogpweb 17899 grm

- _pages/faq.md
**Changes approved by PO**
Updates FAQ page with new content and formatting existing comment
Width for FAQ content is also updated
[Jira Story](https://cm-jira.usa.gov/browse/OGPWEB-17840)
[Preview Link](https://federalist-4be496a3-cca3-4187-b4d4-c3d573ae3139.sites.pages.cloud.gov/preview/gsa/ussm/OGPWEB-17840/faq/)
> Ogpweb 17840

- _includes/scripts.html
Changes approved by PO
RITM1320534
Add dap script
> add dap script

- _includes/scripts.html
Changes approved by PO
RITM1320534
Add dap script
> Staging 2025

- _includes/fibf-circle.html
- _includes/scripts.html
- _layouts/standards.html
- _sass/global.scss
https://cm-jira.usa.gov/browse/OGPWEB-19119
> Ogpweb 19119
